services:
  server:
    build:
      context: .
    volumes:
      - ./server:/app/server
      - ./cache:/app/server/cache
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
      - 9229:9229
